name: Jekyll Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened, edited, ready_for_review ]

jobs:
  printMine:
    name: call production
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: echo ${{ secrets.MY_NUMBER }}*11

  callProduction:    
    name: call production
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
      - name: Call Deploy
        uses: SantaHub/organization/.github/workflows/blank.yml@main
