name: Jekyll Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened, edited, ready_for_review ]

jobs:
  printMine:
    name: Print repo secret
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: echo ${{ secrets.MY_NUMBER }}*11

  prod-secret:
    name: Prod Secret
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Print Secret
        run: echo $(( ${{ secrets.MY_NUMBER }}*11))
      - name : Print Stage
        run : echo "Production"
  
  dev-secret:
    name: Dev Secret
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Print Secret
        run: echo $(( ${{ secrets.MY_NUMBER }}*11 ))
      - name : Print Stage
        run : echo "Dev"

  test-secret:
    name: Test Secret
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Print Secret
        run: echo  $(( ${{ secrets.MY_NUMBER }}*11 ))
      - name: Normal number
        run: echo $(( 2*2 ))
      - name : Print Stage
        run : echo "Test"